ARG BASE_IMAGE=localhost/openstack/openstack-base:latest
FROM ${BASE_IMAGE}

LABEL summary="OpenStack RabbitMQ" \
      io.k8s.description="RabbitMQ messaging service for OpenStack"

RUN uid_gid_manage rabbitmq

COPY rabbitmq/bindeps.txt /tmp/bindeps.txt
RUN pkgs=$(cat /tmp/bindeps.txt | grep -v '^#' | grep -v '^$' | tr '\n' ' ') && \
    if [ -n "${pkgs}" ]; then microdnf -y install ${pkgs} && microdnf clean all && rm -rf /var/cache/dnf; fi && \
    rm /tmp/bindeps.txt && \
    rm -f /etc/rabbitmq/rabbitmq.conf

USER rabbitmq

CMD ["rabbitmq-server"]
